name: py39-similaritysearch
channels:
  - anaconda
  - conda-forge
  - huggingface
dependencies:
  - pip
  - matplotlib=3.5.*
  - pandas=1.4.*
  - python=3.9.*
  - scikit-learn=1.1.*
  - pillow=9.0.*
  - numpy=1.22.*
  - tqdm=4.64.*
  - faiss-gpu=1.7.*
  - pip:
    - opencv-python
    - opencv-contrib-python
    - transformers
    - datasets
